# -*- coding: utf-8 -*-
"""red wine quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yg1T9ICYPI0Y9YI8BbbnC0QUQFx_Tinp
"""

import  pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/winequality-red.csv")
df

df.head()

df.shape

df.isnull().sum()

df.describe()

x=df.drop('quality',axis=1)
x

y=df['quality']
y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

y_pred=rf.predict(x_test)
y_pred

from sklearn.metrics import (accuracy_score, mean_absolute_error, mean_squared_error)
score=accuracy_score(y_pred,y_test)*100
score

mb=mean_absolute_error(y_test,y_pred)
mb

mr=mean_squared_error(y_test,y_pred)
mr

plt.figure(figsize=(10,8))
sns.scatterplot(x='alcohol',y='quality',data=df,color='green',alpha=0.7)
plt.title('Scatter plot of alcohol content vs Quality')
plt.xlabel('Alcohol Content')
plt.ylabel('Quality')
plt.show()

plt.figure(figsize=(10,8))
sns.countplot(x='quality',data=df,palette='coolwarm')
plt.title('Bar Chart of wine quality count')
plt.xlabel('Quality')
plt.ylabel('Count')
plt.show()